# Generated by Django 3.1 on 2020-09-29 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='summary',
            field=models.CharField(default='Summary has not been set', max_length=1200),
        ),
        migrations.AlterField(
            model_name='articles',
            name='articleType',
            field=models.CharField(default='Article Type has not been set', max_length=50),
        ),
        migrations.AlterField(
            model_name='articles',
            name='authors',
            field=models.CharField(default='Authors have not been set', max_length=100),
        ),
        migrations.AlterField(
            model_name='articles',
            name='link',
            field=models.CharField(default='Link has not been set', max_length=200),
        ),
        migrations.AlterField(
            model_name='articles',
            name='tag',
            field=models.CharField(default='Tags have not been set', max_length=400),
        ),
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.CharField(default='Title has not been set', max_length=300),
        ),
        migrations.AlterField(
            model_name='articles',
            name='topics',
            field=models.CharField(default='Topics have not been set', max_length=100),
        ),
    ]
