# Generated by Django 3.1 on 2020-09-29 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20200929_1758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='tag',
            new_name='tags',
        ),
    ]
