# Generated by Django 3.1 on 2020-09-30 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20200929_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='link',
        ),
        migrations.AddField(
            model_name='articles',
            name='documentLink',
            field=models.CharField(default='Document link has not been set', max_length=200),
        ),
        migrations.AddField(
            model_name='articles',
            name='image1Link',
            field=models.CharField(default='Image link 1 has not been set', max_length=200),
        ),
        migrations.AddField(
            model_name='articles',
            name='image2Link',
            field=models.CharField(default='Image link 2 has not been set', max_length=200),
        ),
    ]
