# Generated by Django 3.1 on 2020-10-01 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Title has not been set', max_length=300)),
                ('date', models.DateField(default='Date has not been set')),
                ('countdownDescription', models.CharField(default='Countdown Description has not been set', max_length=200)),
                ('summary', models.CharField(default='Summary has not been set', max_length=1200)),
                ('linkType', models.CharField(default='Coming soon!', max_length=50)),
                ('link', models.CharField(default='Link has not been set', max_length=500)),
            ],
        ),
    ]
