# Generated by Django 3.1 on 2020-10-01 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='imageLink',
            field=models.CharField(default='Image link has not been set', max_length=200),
        ),
    ]
